Notes: Jenkins pipeline
project: icdc
services:
  backend:
    version: 14.5.1.10
    image: 14.5.1.10
    buildNumber: '10'
  frontend:
    version: v3.42.0.10
    image: v3.42.0.10
    buildNumber: '10'
  files:
    version: main.38
    image: main.38
    buildNumber: '38'
