Notes: Jenkins pipeline
project: gmb
services:
  backend:
    version: develop.134
    image: develop.134
    buildNumber: '134'
  frontend:
    version: bento-3.10-branch-update.99
    image: bento-3.10-branch-update.99
    buildNumber: '99'
  auth:
    version: 2.2.0.107
    image: 2.2.0.107
    buildNumber: '107'
  files:
    version: main.65
    image: main.65
    buildNumber: '65'
  users:
    version: 1.3.0.31
    image: 1.3.0.31
    buildNumber: '31'
