Notes: Jenkins pipeline
project: icdc
services:
  backend:
    version: 14.5.1.19
    image: 14.5.1.19
    buildNumber: '19'
  frontend:
    version: v3.49.0.12
    image: v3.49.0.12
    buildNumber: '12'
  files:
    version: 1.4.0.56
    image: 1.4.0.56
    buildNumber: '56'
  interoperation:
    version: main.15
    image: main.15
    buildNumber: '15'
