Notes: Jenkins pipeline
project: icdc
services:
  backend:
    version: main.71
    image: main.71
    buildNumber: '71'
  frontend:
    version: v3.55.0.48
    image: v3.55.0.48
    buildNumber: '48'
  files:
    version: 1.4.0.59
    image: 1.4.0.59
    buildNumber: '59'
  interoperation:
    version: main.34
    image: main.34
    buildNumber: '34'
