Notes: Jenkins pipeline
project: icdc
services:
  backend:
    version: 4.8.0.224
    image: 4.8.0.224
    buildNumber: '224'
  frontend:
    version: 3.9.0.85
    image: 3.9.0.85
    buildNumber: '85'
  files:
    version: main.34
    image: main.34
    buildNumber: '34'
