Notes: Jenkins pipeline
project: bento
services:
  backend:
    version: develop-4.7.0-26
    image: develop-4.7.0-26
    buildNumber: '26'
  frontend:
    version: develop.78
    image: develop.78
    buildNumber: '78'
