Notes: Jenkins pipeline
project: icdc
services:
  backend:
    version: 14.5.1.13
    image: 14.5.1.13
    buildNumber: '13'
  frontend:
    version: v3.42.0.41
    image: v3.42.0.41
    buildNumber: '41'
  files:
    version: main.38
    image: main.38
    buildNumber: '38'
