- name: build frontend microservice
  hosts: all
  connection: local
  gather_facts: yes
  become: yes

  tasks:
    #install collections
    - name: install collections
      shell: "ansible-galaxy collection install {{ item | quote }} --force"
      loop:
        - community.docker:<=3.4.3
        - amazon.aws:<=5.4.0
        - community.aws:<=3.2.0
        -  git+https://github.com/CBIIT/datacommons-devops.git#/ansible/collections/bento/common/,gmb

    #docker login
    - name: docker login
      include_role:
        name: bento.common.ecr_login
      vars:
        region: us-east-1

    #frontend build
    - name: build frontend
      include_role:
        name: bento.common.build_frontend
        apply:
          environment:
            NODE_OPTIONS: '--max-old-space-size=4096'
      vars:
        ansible_python_interpreter: /usr/bin/python3
        workspace: "{{ lookup('env','WORKSPACE') }}"
        build_number: "{{ lookup('env','BUILD_NUMBER')}}"
        project_name: "{{ lookup('env','PROJECT') }}"
        image_version: "{{ lookup('env','FE_VERSION') }}"
        container_name: "frontend"
        #container_build_path: "{{ workspace }}/{{ project_name }}-frontend"
        container_build_path: "{{ workspace }}/gmb-frontend"
        dockerfile_path: "{{ workspace }}/playbooks/docker/dockerfiles/frontend-microservice-dockerfile"
        container_registry_url: "{{ ecr_repo }}"
