---
- name: gmb-etl extract only
  hosts: loader
  connection: local
  gather_facts: yes
  become: yes

  tasks:
  #install collections
   # - name: install aws collection
   #   shell: "ansible-galaxy collection install {{ item | quote }} --force"
   #   loop:
       # - community.docker:<=3.4.3
       # - amazon.aws:<=5.4.0
       # - community.aws:<=3.2.0

    - name: perform data loading
      include_role:
        name: gmb-etl
        tasks_from: extract
      vars:
        ansible_python_interpreter: /usr/bin/python3
